config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'settings' => 'settings#change'
  get 'settings_save' => 'settings#set'
  get 'forecast/hourly' => 'forecast#hourly'
  get 'forecast/daily' => 'forecast#daily'

  get 'directions' => 'directions#search'
  get 'directions_plan' => 'directions#plan'
  get 'news' => 'news#news'
  get 'news_article' => 'news#article'
  get 'news_search' => 'news#search'
  # Defines the root path route ("/")
  root 'index#index'
end

app/controllers/news_controller.rb
# frozen_string_literal: true

require 'uri'
require 'open-uri'
require 'action_view'
require 'net/http'
require 'gnews'
require 'scraper'

class NewsController < ApplicationController
  include ActionView::Helpers::SanitizeHelper
  include Scraper
  def news
    @gnews = gnews
    change_section
    get_articles
    prepare_articles

    render :list
  end

  def article
    @article_url = params[:article]
    @article = scrape_article(@article_url).html_safe
    render :article
  end

  def change_section
    @section = params[:section] || cookies['news_default_section']
    gnews.change_section(@section)
  end

  def search
    @search_query = params[:search_query]
    get_articles
    prepare_articles
    render :list
  end

  private

  def get_blacklist
    ['Financial Times',
    'Bloomberg',
    'Times of Israel',
    'Times of India',
    'Reuters',
    'Daily Record',
    'Live updates',
    'Wall Street Journal',
    'Fox News',
    'USA TODAY',
    'Axios',
    'SFGATE',
    'Ynetnews',
    'KABC-TV']
end

  def prepare_articles
    @news_items = []
    @articles.each_with_index do |item, i|
      @news_items[i] = { item_title: item['title'].rpartition('-')[0] }
      @item_articles = []
      item['description'].gsub('<ol>', '').gsub('</ol>', '').gsub('</li>',
                                                                  '</li>splitme').split('splitme').each do |article|
        next if get_blacklist.any? { |news_site| article.include? news_site }

        @item_articles << { article_title: strip_links(article).html_safe,
                            article_url: URI.extract(article, /http(s)?/)[0] }
      end
      @news_items[i][:articles] = @item_articles
    end
  end

  def scrape_article(url)
    url = gnews.get_article(url)

    @article_url = url
    Scraper.scrape_article(@article_url, gnews.get_useragent)
  end

  def get_articles
    @articles, @title = gnews.get_articles_from_api(@search_query)
  end

  def gnews
    @gnews ||= Gnews.new({
      section: cookies['news_default_section'],
      country_code: cookies['country_code']
    })
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/article.html.erb
<div class="news">
<%= link_to "Read the original source here", sanitize(@article_url.html_safe)  %><br />
<%= @article %>
</div>

app/views/news/list.html.erb
<div class='news_topics'>
<%= @title %><br /><br />
    <%= link_to 'Headlines', news_path({section: 'HEADLINES'}) %> |
    <%= link_to 'World', news_path({section: 'WORLD'}) %> |  <%= link_to 'Nation', news_path({section:'NATION'}) %> |
    <%= link_to 'Business', news_path({section: 'BUSINESS'}) %> |  <%= link_to 'Technology', news_path({section:'TECHNOLOGY'}) %> |
    <%= link_to 'Entertainment', news_path({section: 'ENTERTAINMENT'}) %> |  <%= link_to 'Science', news_path({section:'SCIENCE'}) %> |
    <%= link_to 'Sports', news_path({section: 'SPORTS'}) %> |  <%= link_to 'Health', news_path({section:'HEALTH'}) %>
</div>
<br />
<div class='news_search'>
<%= form_with url:"news_search", method: :get, local: true do |f| %>
    <%= f.label "Search news" %>
    <%= f.text_field :search_query, class: "text_field" %>
    <br /><br />
    <%= f.submit "Search" %>
  <% end %>
</div>
<br /><br />
<div class="news">
    <% @news_items.each do |item| %>
            <b><%= item[:item_title] %></b><br />
            <ul>
            <% item[:articles].each do |article| %>
                <%= link_to article[:article_title], news_article_path(article: article[:article_url]) %>
            <% end %>
            </ul>
            <br />
    <% end %>
</div>